using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace InfinityOfficialNetwork.Languages.IXX;


// ============================================================================
//               PHASE 3: BACKEND CODE GENERATOR (LLVM IR EMITTER)
// ============================================================================
public class LlvmIrGeneratorVisitor : IAsgVisitor<string>
{
	private readonly StringBuilder _sb = new();
	private int _registerCount = 1;
	private int _labelCount = 1;
	private bool _isTerminated = false;

	// Direct Graph Mapping! 
	private readonly Dictionary<AsgStatement, (string ContinueLabel, string BreakLabel)> _loopLabels = new();

	private string NextRegister(string hint = "t") => $"%.{hint}.{_registerCount++}";
	private string CreateLabel(string prefix) => $"%{prefix}.{_labelCount++}";
	private string GetDefaultValue(TypeInfo type) => type.IsFloat ? "0.0" : (type.IsBool ? "false" : "0");

	private void EmitComment(string comment, string indent = "  ")
	{
		if (string.IsNullOrWhiteSpace(comment)) return;
		foreach (var line in comment.Split('\n')) _sb.AppendLine($"{indent}; {line.Trim('\r')}");
	}

	public string GenerateModule(List<AsgFunction> functions)
	{
		_sb.Clear();
		_sb.AppendLine("; Generated by InfinityOfficialNetwork IXX Compiler");
		foreach (var func in functions) func.Accept(this);
		return _sb.ToString();
	}

	public string Visit(AsgFunction node)
	{
		_registerCount = 1;
		_labelCount = 1;
		_isTerminated = false;
		_loopLabels.Clear();

		EmitComment(node.Comment, "");

		var args = string.Join(", ", node.Symbol.Parameters.Select(p => $"{p.Type.ToLlvmType()} %{p.Name}"));
		_sb.AppendLine($"define {node.Symbol.ReturnType.ToLlvmType()} @{node.Symbol.Name}({args}) {{");
		foreach (var stmt in node.Body) stmt.Accept(this);
		_sb.AppendLine("}\n");
		return null;
	}

	public string Visit(AsgReturn node)
	{
		EmitComment(node.Comment);
		var exprVal = node.Expression.Accept(this);
		_sb.AppendLine($"  ret {node.Expression.Type.ToLlvmType()} {exprVal}");
		_isTerminated = true;
		return null;
	}

	public string Visit(AsgVariableDecl node)
	{
		EmitComment(node.Comment);
		string llvmType = node.Symbol.Type.ToLlvmType();
		_sb.AppendLine($"  %{node.Symbol.Name} = alloca {llvmType}");

		string initVal = node.InitialValue != null ? node.InitialValue.Accept(this) : GetDefaultValue(node.Symbol.Type);
		_sb.AppendLine($"  store {llvmType} {initVal}, {llvmType}* %{node.Symbol.Name}");
		return null;
	}

	public string Visit(AsgAssignment node)
	{
		EmitComment(node.Comment);
		var exprVal = node.Expression.Accept(this);
		string llvmType = node.Symbol.Type.ToLlvmType();
		_sb.AppendLine($"  store {llvmType} {exprVal}, {llvmType}* %{node.Symbol.Name}");
		return null;
	}

	public string Visit(AsgBlock node)
	{
		EmitComment(node.Comment);
		foreach (var stmt in node.Statements)
		{
			if (_isTerminated) break;
			stmt.Accept(this);
		}
		return null;
	}

	public string Visit(AsgIf node)
	{
		EmitComment(node.Comment);
		var condVal = node.Condition.Accept(this);

		string thenLabel = CreateLabel("if.then");
		string elseLabel = node.ElseBranch != null ? CreateLabel("if.else") : null;
		string mergeLabel = CreateLabel("if.merge");

		_sb.AppendLine(elseLabel != null ? $"  br i1 {condVal}, label {thenLabel}, label {elseLabel}" : $"  br i1 {condVal}, label {thenLabel}, label {mergeLabel}");

		_sb.AppendLine($"{thenLabel.Substring(1)}:");
		_isTerminated = false;
		node.ThenBranch.Accept(this);
		if (!_isTerminated) _sb.AppendLine($"  br label {mergeLabel}");

		if (elseLabel != null)
		{
			_sb.AppendLine($"{elseLabel.Substring(1)}:");
			_isTerminated = false;
			node.ElseBranch.Accept(this);
			if (!_isTerminated) _sb.AppendLine($"  br label {mergeLabel}");
		}

		_sb.AppendLine($"{mergeLabel.Substring(1)}:");
		_isTerminated = false;
		return null;
	}

	public string Visit(AsgWhile node)
	{
		EmitComment(node.Comment);
		string headerLabel = CreateLabel("while.header");
		string bodyLabel = CreateLabel("while.body");
		string exitLabel = CreateLabel("while.exit");

		// Bind Graph Labels for lookup during nested loop control processing
		_loopLabels[node] = (headerLabel, exitLabel);

		if (!_isTerminated) _sb.AppendLine($"  br label {headerLabel}");

		_sb.AppendLine($"{headerLabel.Substring(1)}:");
		_isTerminated = false;

		var condVal = node.Condition.Accept(this);
		_sb.AppendLine($"  br i1 {condVal}, label {bodyLabel}, label {exitLabel}");

		_sb.AppendLine($"{bodyLabel.Substring(1)}:");
		_isTerminated = false;

		node.Body.Accept(this);

		if (!_isTerminated) _sb.AppendLine($"  br label {headerLabel}");

		_sb.AppendLine($"{exitLabel.Substring(1)}:");
		_isTerminated = false;
		return null;
	}

	public string Visit(AsgDoWhile node)
	{
		EmitComment(node.Comment);
		string bodyLabel = CreateLabel("do.body");
		string condLabel = CreateLabel("do.cond");
		string exitLabel = CreateLabel("do.exit");

		_loopLabels[node] = (condLabel, exitLabel);

		if (!_isTerminated) _sb.AppendLine($"  br label {bodyLabel}");

		_sb.AppendLine($"{bodyLabel.Substring(1)}:");
		_isTerminated = false;

		node.Body.Accept(this);

		if (!_isTerminated) _sb.AppendLine($"  br label {condLabel}");

		_sb.AppendLine($"{condLabel.Substring(1)}:");
		_isTerminated = false;

		var condVal = node.Condition.Accept(this);
		_sb.AppendLine($"  br i1 {condVal}, label {bodyLabel}, label {exitLabel}");

		_sb.AppendLine($"{exitLabel.Substring(1)}:");
		_isTerminated = false;
		return null;
	}

	public string Visit(AsgLoopControl node)
	{
		EmitComment(node.Comment);

		string targetLabel = null;
		foreach (var action in node.Actions)
		{
			var labels = _loopLabels[action.TargetLoop];
			if (action.Action == TokenType.Continue) { targetLabel = labels.ContinueLabel; break; }
			else if (action.Action == TokenType.Break) { targetLabel = labels.BreakLabel; }
		}

		if (targetLabel != null) { _sb.AppendLine($"  br label {targetLabel}"); _isTerminated = true; }
		return null;
	}

	public string Visit(AsgConstant node) => node.Value;

	public string Visit(AsgVariableAccess node)
	{
		if (node.Symbol.IsLocal)
		{
			string reg = NextRegister($"{node.Symbol.Name}.val");
			string llvmType = node.Type.ToLlvmType();
			_sb.AppendLine($"  {reg} = load {llvmType}, {llvmType}* %{node.Symbol.Name}");
			return reg;
		}
		return $"%{node.Symbol.Name}";
	}

	public string Visit(AsgBinaryOperation node)
	{
		var leftVal = node.Left.Accept(this);
		var rightVal = node.Right.Accept(this);

		if (node.Operator is TokenType.DoubleAmpersand or TokenType.DoubleBar)
		{
			string logicalOp = node.Operator == TokenType.DoubleAmpersand ? "and" : "or";
			string logicalReg = NextRegister("log");
			_sb.AppendLine($"  {logicalReg} = {logicalOp} i1 {leftVal}, {rightVal}");
			return logicalReg;
		}

		string llvmType = node.Left.Type.ToLlvmType();

		string reg = NextRegister(node.Operator switch
		{
			TokenType.Plus => "add",
			TokenType.Minus => "sub",
			TokenType.Star => "mul",
			TokenType.Slash => "div",
			TokenType.Ampersand => "and",
			TokenType.Bar => "or",
			TokenType.Caret => "xor",
			_ => "cmp"
		});

		if (node.Operator is TokenType.DoubleEqual or TokenType.NotEqual or TokenType.LessThan or TokenType.LessEqual or TokenType.GreaterThan or TokenType.GreaterEqual)
		{
			string cond;
			if (node.Left.Type.IsFloat)
			{
				cond = node.Operator switch { TokenType.DoubleEqual => "oeq", TokenType.NotEqual => "one", TokenType.LessThan => "olt", TokenType.LessEqual => "ole", TokenType.GreaterThan => "ogt", TokenType.GreaterEqual => "oge", _ => "oeq" };
				_sb.AppendLine($"  {reg} = fcmp {cond} {llvmType} {leftVal}, {rightVal}");
			}
			else
			{
				bool signed = node.Left.Type.IsSigned;
				cond = node.Operator switch { TokenType.DoubleEqual => "eq", TokenType.NotEqual => "ne", TokenType.LessThan => signed ? "slt" : "ult", TokenType.LessEqual => signed ? "sle" : "ule", TokenType.GreaterThan => signed ? "sgt" : "ugt", TokenType.GreaterEqual => signed ? "sge" : "uge", _ => "eq" };
				_sb.AppendLine($"  {reg} = icmp {cond} {llvmType} {leftVal}, {rightVal}");
			}
			return reg;
		}

		string op = node.Left.Type.IsFloat
			? node.Operator switch { TokenType.Plus => "fadd", TokenType.Minus => "fsub", TokenType.Star => "fmul", TokenType.Slash => "fdiv", _ => "fadd" }
			: node.Operator switch { TokenType.Plus => "add", TokenType.Minus => "sub", TokenType.Star => "mul", TokenType.Slash => node.Left.Type.IsSigned ? "sdiv" : "udiv", TokenType.Ampersand => "and", TokenType.Bar => "or", TokenType.Caret => "xor", _ => "add" };

		_sb.AppendLine($"  {reg} = {op} {llvmType} {leftVal}, {rightVal}");
		return reg;
	}

	public string Visit(AsgFunctionCall node)
	{
		var evaluatedArgs = node.Arguments.Select(arg => $"{arg.Type.ToLlvmType()} {arg.Accept(this)}");
		string reg = NextRegister($"{node.Symbol.Name}.res");
		_sb.AppendLine($"  {reg} = call {node.Type.ToLlvmType()} @{node.Symbol.Name}({string.Join(", ", evaluatedArgs)})");
		return reg;
	}

	public string Visit(AsgCast node)
	{
		string val = node.Expression.Accept(this);
		TypeInfo from = node.Expression.Type;
		TypeInfo to = node.Type;

		if (from == to) return val;
		if (from.ToLlvmType() == to.ToLlvmType()) return val;

		string reg = NextRegister("cast");
		string fromLlvm = from.ToLlvmType();
		string toLlvm = to.ToLlvmType();

		if (from.IsBool) { _sb.AppendLine(to.IsInteger ? $"  {reg} = zext i1 {val} to {toLlvm}" : $"  %.t{_registerCount} = zext i1 {val} to i32\n  {reg} = uitofp i32 %.t{_registerCount++} to {toLlvm}"); }
		else if (to.IsBool) { _sb.AppendLine(from.IsFloat ? $"  {reg} = fcmp une {fromLlvm} {val}, 0.0" : $"  {reg} = icmp ne {fromLlvm} {val}, 0"); }
		else if (from.IsInteger && to.IsInteger) { _sb.AppendLine(from.Bits < to.Bits ? $"  {reg} = {(from.IsSigned ? "sext" : "zext")} {fromLlvm} {val} to {toLlvm}" : $"  {reg} = trunc {fromLlvm} {val} to {toLlvm}"); }
		else if (from.IsFloat && to.IsFloat) { _sb.AppendLine(from.Bits < to.Bits ? $"  {reg} = fpext {fromLlvm} {val} to {toLlvm}" : $"  {reg} = fptrunc {fromLlvm} {val} to {toLlvm}"); }
		else if (from.IsInteger && to.IsFloat) { _sb.AppendLine($"  {reg} = {(from.IsSigned ? "sitofp" : "uitofp")} {fromLlvm} {val} to {toLlvm}"); }
		else if (from.IsFloat && to.IsInteger) { _sb.AppendLine($"  {reg} = {(to.IsSigned ? "fptosi" : "fptoui")} {fromLlvm} {val} to {toLlvm}"); }
		else if (from.IsByte || to.IsByte) { _sb.AppendLine($"  {reg} = zext i8 {val} to {toLlvm}"); } // Bypass fallback logic to avoid return mismatches

		return reg;
	}

	public string Visit(AsgUnaryOperation node)
	{
		var val = node.Expression.Accept(this);
		string reg = NextRegister("un");

		if (node.Operator == TokenType.Exclamation) { _sb.AppendLine($"  {reg} = xor i1 {val}, true"); return reg; }
		if (node.Operator == TokenType.Tilde) { string mask = node.Type.IsBool ? "true" : "-1"; _sb.AppendLine($"  {reg} = xor {node.Type.ToLlvmType()} {val}, {mask}"); return reg; }
		return reg;
	}

	public string Visit(AsgErrorStatement node) => null;
	public string Visit(AsgErrorExpression node) => "0";
}
